abstract class GoWheelsStates{}
class GoWheelsInitialState extends GoWheelsStates{}
class SignUpState extends GoWheelsStates{}
class LogInState extends GoWheelsStates{}
class ResetPasswordState extends GoWheelsStates{}
class GetPermissionRoleState extends GoWheelsStates{}
class SignOutState extends GoWheelsStates{}
class GetCarsListState extends GoWheelsStates{}
class AddNewCarState extends GoWheelsStates{}
class DeleteCarState extends GoWheelsStates{}
class GetRentSDetailsState extends GoWheelsStates{}
class GetMoreRentsDetailsState extends GoWheelsStates{}
class AddRentDetailState extends GoWheelsStates{}
class EditRentDetailState extends GoWheelsStates{}
class AddPaymentState extends GoWheelsStates{}
class AddIncomeState extends GoWheelsStates{}
class GetTotalRevenueState extends GoWheelsStates{}
class GetPaymentsState extends GoWheelsStates{}
class GetIncomeState extends GoWheelsStates{}